name: flutter_ravepay_example
description: Demonstrates how to use the flutter_ravepay plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ravepay:
    path: ../

flutter:
  uses-material-design: true
